### ISSUE TITLE
Modification categorie Generale

### ISSUE THREAD

**Issue by IUTLucas** [GroupeSAETPA1/Quiz#113]
## Description

Possibilité de modifier la catégorie générale

## Étape pour reproduire le bug

  1. Aller sur modifier catégorie
  2. Cliquez sur modifier général
  3. Changer le nom
  4. Le nom est changer

## Comportement attendu

Impossibilité de modifier général

**Comment by TomDouaud** [comment]
@Francois389 a fixé ce bug
