### ISSUE TITLE
Fichier corrompu

### ISSUE THREAD

**Issue by IUTLucas** [GroupeSAETPA1/Quiz#120]
## Description

Le fichier de question serialisé est corrompu

## Étape pour reproduire le bug

1. Aller ecrire n'importe quoi dans le fichier serialisé des questions
2. Lancer l'application

## Comportement attendu

Pop up avec un message ressemblant a : Fichier de sauvegarde des questions a été corrompu . Impossible d'importer les questions précédemment enregistré

## Captures d'écran 

![image](https://github.com/GroupeSAETPA1/Quiz/assets/133020052/9812465a-ee2f-46a1-8469-d552327b641d)

**Comment by TomDouaud** [comment]
bug fixed sur sprint 3
