### ISSUE TITLE
Supprimer catégorie

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#14]
## US

En tant que utilisateur
Je peut supprimer une catégorie
Afin de retirer celle ci

## Test d'acceptation

![Image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/7f90c848-676a-4371-924d-90044a7f76ac)

### GIVEN 

un utilisateur sur la page éditeur de questions

### WHEN 

il clique sur modifier une catégorie

### THEN

il voit la liste des catégories

___ 

### GIVEN 

un utilisateur sur la page modifier catégories

### WHEN 

il clique sur le bouton supprimer de la catégorie qu'il souhaite supprimer

### THEN

un fenêtre de confirmation lui demande si il est sur

___ 

### GIVEN 

un utilisateur sur la fenêtre de confirmation de suppression

### WHEN 

il clique sur le bouton supprimer

### THEN

la catégorie en question est supprimée 

## Pondération

5

**Comment by TomDouaud** [comment]
Il manque le cas limite ou l'utilisateur annule la suppression lors de la fenêtre de confirmation @quentinformatique
