### ISSUE TITLE
Connexion client

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#21]
## US

En tant que utilisateur
Je peux me connecter en tant que client
Afin de récupérer des questions envoyées par le serveur

## Test d'acceptation

1)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/69b84235-f543-43ad-b40f-bf46da1b4df5)

### GIVEN 

un utilisateur sur la page d'accueil

### WHEN 

il clique sur mode en ligne

### THEN

il arrive sur la page du mode en ligne

___ 

### GIVEN 

un utilisateur sur la page du mode en ligne

### WHEN 

il clique sur me connecter en tant que client

### THEN

il est connecté en tant que client

___ 

### GIVEN 

un utilisateur sur la page mode en ligne

### WHEN 

il est connecté en tant que client

### THEN
il peut recevoir des questions

## Pondération

8

**Comment by quentinformatique** [comment]
En tant que utilisateur
je peut me connecter avec d'autres pc en tant que client
afin de récupérer des questions envoyées par le serveur

**Comment by Francois389** [comment]
C'est obligatoire de ce connecter avec d'auter PC ?
