### ISSUE TITLE
Modification categorie question

### ISSUE THREAD

**Issue by IUTLucas** [GroupeSAETPA1/Quiz#22]
## US

En tant qu'utilisateur
Je peut modifier la catégorie actuelle d'une question existante
Afin d'adapter la catégorie a une qui correspond mieux

## Test d'acceptation ##

![Image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/54468ced-b371-4dc4-9a2c-6b1651b1a4c6)

** Cas nominal : **
Etant donné un utilisateur
Il clique sur le bouton de modification des paramètres de la question
Un menu s'ouvre sur lui demandant de modifier les paramètres de la question

** Cas nominal : ** 
Etant donné un utilisateur sur le menu de modification d'une question
Il choisis une nouvelle catégorie dans la liste des catégorie existante
Une pop-up s'ouvre lui indiquant que la catégorie a bien été modifié

** Cas limite : **
Etant donné un utilisateur sur le menu de modification d'une question
Il appui sur le bouton cancel
Il revient sur le menu de modification d'une question

## Pondération

4

**Comment by Francois389** [comment]
"modifier la catégorie d'une question existente" ?
