### ISSUE TITLE
Choix nombre question

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#24]
## US

En tant qu'utilisateur
Je veux choisir le nombre de question
Afin de faire des sessions de durée différente

## Test d'acceptation

![Image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/9771ba6f-de2f-4924-a762-12b3b68ee886)

### Given

Un utilisateur sur la page de configuration des questionnaires
 
### When

L'utilisateur choisi un nombre de question

### Then

Le questionnaire aura le nombre de question choisi

## Pondération

1

**Comment by quentinformatique** [comment]
bien
