### ISSUE TITLE
Choix export

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#25]
## US

En tant que utilisateur
Je peut choisir les questions que je veux envoyer
Afin de partager certaines questions ou catégories

1)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/ad2ea351-084e-4a4f-8ece-6b8ab0406bcd)

2)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/10d48560-10e4-4978-b187-c808729424bc)

### GIVEN 

un utilisateur sur la page mode en ligne 

### WHEN 

il peut se connecter en tant que serveur

### THEN

il choisit les questions qu'il veut envoyer

___ 

### GIVEN 

un utilisateur sur la page mode en ligne connecter en tant que serveur

### WHEN 

il choisit les questions qu'il veut envoyer et les envoies

### THEN

les utilisateurs connectés en tant que clients reçoivent les questions

## Pondération

35

**Comment by quentinformatique** [comment]
En tant que utilisateur
Je peut choisir les questions que je veut envoyer
Afin de partager certaines questions ou catégories

**Comment by TomDouaud** [comment]
Il faut peut etre préciser que c'est quand l'utilisateur est connecté et en mode serveur dans le "En tant que"
