### ISSUE TITLE
Modification difficulté question

### ISSUE THREAD

**Issue by IUTLucas** [GroupeSAETPA1/Quiz#26]
## US

En tant qu'utilisateur
Je peut modifier la difficulté d'une question
Afin de rééquilibre la difficulté des questionnaires

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/0255baa3-ef52-416c-9466-3d665310fec1)

## Test d'acceptation 

**Cas nominal :**
Etant donné un utilisateur
Il clique sur le bouton de modification des paramètres de la question
Un menu s'ouvre lui demandant de modifier les paramètres de la question

**Cas nominal :** 
Étant donné un utilisateur sur le menu de modification d'une question
Il choisis une nouvelle difficulté dans la liste et appuis sur validé
Une pop-up s'ouvre lui indiquant que la difficulté a bien été modifié

**Cas limite :**
Étant donné un utilisateur sur le menu de modification d'une question
Il appui sur le bouton cancel
Il revient sur le menu de modification des questions

## Pondération

5

**Comment by TomDouaud** [comment]
L'US a l'air d'etre supprimée, mais, ca pourait etre ca :
En tant qu'utilisateur
Je peut modifier la difficultée d'une question
Afin de re-balancer la difficultée des questionnaires

**Comment by TomDouaud** [comment]
Est ce qu'on fait toujours avec un menu qui s'ouvre ou on change directement comme dans le proto IHM ?

**Comment by TomDouaud** [comment]
Finalement on fait avec une page dédiée
