### ISSUE TITLE
Passer la question

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#28]
## US

En tant qu'utilisateur
Je veux ne pas choisir une réponse au question
Afin de passer à la suivante

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/d2857d2d-1aae-4856-9b91-ee7b0e77b6b5)

### Given

Une question du questionnaire, dont l'utilisateur ne connait pas la réponse

### When

Il clique sur Passer

### Then

L'application affiche la question suivante et compte une réponse fausse pour la question précédente

---

### Given

Une question du questionnaire et un choix de réponse sélectionné
 
### When

L'utilisateur clique sur Passer

### Then

L'application affiche la question suivante et compte une réponse fausse pour la question précédente

## Pondération

1

**Comment by quentinformatique** [comment]
"je veut ne peux" ???

**Comment by TomDouaud** [comment]
Ce ne serait pas mieux un titre plus explicite du genre : Passer la question ?
