### ISSUE TITLE
Selection de la réponse

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#29]
## US

En tant qu'utilisateur
Je veux sélectionner un choix avant de valider ma réponse
Afin de pouvoir la modifier si je me rend compte d'une erreur

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/45e1bf42-f202-420f-9f7f-5d6f3f54a2b7)

### Given

Une question du questionnaire
 
### When

L'utilisateur clique sur un des choix de réponse

### Then

Il peut encore changer de proposition de réponse

## Pondération

1

**Comment by quentinformatique** [comment]
mouais, mal formuler, j'ai quand même compris mais c'est bizarre
