### ISSUE TITLE
Statistique des réponses

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#30]
## US

En tant qu'utilisateur
Je veux avoir une statistique du nombre de réponse juste
Afin de voir mon amélioration au fil des tentatives

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/5a349393-6340-469d-ac77-f14f0f11715c)

### Given

L'utilisateur est à la dernière question de son questionnaire
 
### When

Il clique sur Suivant

### Then

La page de résultat s'affiche avec son score de bonne réponse

## Pondération

2

**Comment by quentinformatique** [comment]
faut de copie : "file"
