### ISSUE TITLE
Pas suffisament de question

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#33]
## US

En tant qu'utilisateur
Je veux être informer s'il n'y a pas assez de question
Afin de ne pas être surpris par le peu de question proposé

1)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/cafce5e0-f510-4dce-94b6-e882a3dd847a)

2)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/4ab0a1b6-fd02-4793-9032-afa021c1350c)

### Given

Un paramétrage de questionnaire, ne permettant pas de fournir suffisamment de question à l'utilisateur
 
### When

L'utilisateur appuie sur le bouton Jouer

### Then

Un message s'affiche pour lui indiquer le manque de question lié à ses critères

### Given

Un utilisateur sur le pop-up "pas assez de questions"
 
### When

L'utilisateur appuie sur le bouton Lancer le questionnaire

### Then

Le Questionnaire se lance avec le peu de question disponibles

### Given

Un utilisateur sur le pop-up "pas assez de questions"
 
### When

L'utilisateur appuie sur le bouton Revenir en arrière

### Then

L'utilisateur revient sur le paramétrage du Questionnaire pour changer ses paramètres

## Pondération

3

**Comment by quentinformatique** [comment]
bien

**Comment by TomDouaud** [comment]
L'issue #32 et #33 ne sont pas les memes ?

**Comment by Francois389** [comment]
Non c'est quand, il n'y a pas assez de question disponible pour faire un questionnaire avec le nombre de questions demandé.
