### ISSUE TITLE
Importation de question

### ISSUE THREAD

**Issue by TomDouaud** [GroupeSAETPA1/Quiz#34]
En tant qu'utilisateur
Je veut sélectionner un fichier csv
Afin d'importer des questions

1)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/2e155dc3-2d75-47d3-afda-7da873790e10)

2)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/f07df219-0f9f-4bd0-9491-e59784a07ed8)

### **TEST ACCEPTATION :**

**Cas nominal :** 

Étant donné un utilisateur sur la fenêtre importer des questions
Quand je choisit mon fichier de question .csv valide
Alors les questions sont importées et j'ai un message de confirmation

**Cas limite :** 

Étant donné un utilisateur sur la fenêtre importer des questions
Quand j'importe un fichier de question valide mais avec une/des nouvelles catégories
Alors les questions et catégories sont importées et j'ai un message de confirmation

Étant donné un utilisateur sur la fenêtre importer des questions
Quand j'importe un fichier de question partiellement valide
Alors les questions valides sont importées et je suis informé de l'échec de l'import total

**Cas d'erreur :** 

Étant donné un utilisateur sur la fenêtre importer des questions
Quand je choisit un fichier de question .csv au mauvais format
Alors un message d'erreur explicite apparait

Étant donné un utilisateur sur la fenêtre importer des questions
Quand je choisit un fichier d'un autre type que csv
Alors un message d'erreur explicite apparait

## Pondération

6

**Comment by quentinformatique** [comment]
précise sur quelle fenetre tu es pour faire tout ça dans tes test d'acceptations

**Comment by TomDouaud** [comment]
Comme ca ca va chef ? @quentinformatique

**Comment by TomDouaud** [comment]
c'est bon tout est reglé
