### ISSUE TITLE
Reception de Question

### ISSUE THREAD

**Issue by TomDouaud** [GroupeSAETPA1/Quiz#35]
En tant qu'utilisateur en mode client
Je veut recevoir des questions
Afin de ne pas a les réécrire

1)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/296fc5a4-75c1-4e8a-a3a6-84e822d544b0)

2)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/8bfe3520-a71b-4e54-8de0-58fb63c1ba6f)

### **TEST ACCEPTATION :**

**Cas nominal :** 

Étant donné un utilisateur en mode client
Quand il clique pour réceptionner des questions
Alors l'ordinateur reçoit les questions du serveur

**Cas d'erreur :** 

Étant donné un utilisateur en mode client avec des problèmes de connexion
Quand il clique pour réceptionner des questions 
Alors l'ordinateur affiche un message d'erreur

## Pondération

17

**Comment by quentinformatique** [comment]
l'utilisateur ne "télécharge" pas les question, il les reçoit du serveur
