### ISSUE TITLE
Créer une question

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Quiz#39]
## US

En tant que USER 
Je peux ajouter des questions 
Afin d'apporter de la variété au quizz

# TEST D'ACCEPTATION 

## cas nominal : 

***Étant donnée*** un utilisateur avec une question ou les champs sont rentré et respecté
***Quand*** il clique sur ajouter une question 
***Alors*** celle-ci est ajouté à la banque de question

## cas d'erreur : 

***Etant donnée*** un utilisateur avec une question ou des champs ne sont pas rentré ou pas respecté
***Quand*** il ne choisit pas de difficulté et clique sur ajouter une question 
***Alors*** une pop-up s'ouvre demander de corriger les erreurs

## Pondération

10

**Comment by Francois389** [comment]
Faire une Business Rule
