### ISSUE TITLE
Le nom de l'utilisateur

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#54]
## US

En tant qu'utilisateur 
Je veux renseigner son nom 
Afin de personnaliser les messages informant des résultats

## Test d'acceptation

***Given*** un utilisateur sur le page des paramétres, qui a remplie le champs "Nom"
***When*** il clique sur "Sauvegarder"
***Then*** le message récapitulant les résultats est personalisé

***Given*** un utilisateur finissant un questionnaire, il n'a pas enregistrer son nom
***When*** il termine le questionnaire
***Then*** Un message non personalisé apparait

**Comment by TomDouaud** [comment]
Le profil est maintenant sur la page principale
