### ISSUE TITLE
Créer categorie

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#6]
## US

En tant que utilisateur
Je peut créer des catégories
Afin de séparer les types de questions

## Test d'acceptation

![Image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/0893a794-cb66-4b7d-bbc7-c31869ff2edb)

### GIVEN 

un utilisateur sur la page Editeur de questions

### WHEN 

il clique sur créer une catégorie

### THEN

il rentre le nom de la catégorie

___ 

### GIVEN 

un utilisateur sur la page de création de catégorie

### WHEN 

il clique sur valider une fois que le nom est rentré

### THEN

la nouvelle catégorie est crée

**Cas d'erreur**
___ 

### GIVEN 

un utilisateur sur la page de création de catégorie

### WHEN 

il clique sur valider mais le nom n'est pas rentré

### THEN

la nouvelle catégorie n'est pas crée et un message d'erreur apparait

___ 

### GIVEN 

un utilisateur sur la page de création de catégorie

### WHEN 

il clique sur valider mais le nom de catégorie existe déjà

### THEN

la nouvelle catégorie n'est pas crée et un message d'erreur apparait

## Pondération

3

**Comment by quentinformatique** [comment]
En tant que utilisateur
Je peut créer des catégories
Afin de séparer les types de questions

**Comment by Francois389** [comment]
👍
