### ISSUE TITLE
Création d'une question sans Catégorie

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#69]
## Description

Il est possible de créer une question spécifier une catégorie

## Étape pour reproduire le bug

1. Aller sur la page Création Question ou Catégorie
2. Ne pas sélectionner de Catégorie
3. Remplissez tout les champs
4. Cliquez sur Valider
5. **On indique à l'utilisateur que la question est créer**

## Comportement attendu

Afficher un message d'erreur demandant à l'utilisateur de sélectionner une catégorie

**Comment by TomDouaud** [comment]
Bug réparé avec la branche bug#77
