### ISSUE TITLE
pas de retour utilisateur lors de l'echec d'une création de question

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#70]
**Décrivez le bug**
Quand on crée une question mais qu'il il a une une erreur (ex: champ non rempli) il n'y a pas de retour a l'ulisateur, juste une erreur dans la console

**Pour le reproduire**
Étape pour reproduire le bug
1. Aller sur la page 'CreationQuestionEtCategorie'
2. Cliquez sur 'Valider' alors que tout les champs ne sont pas remplis
4. **L'erreur apparait**

**Comportement attendu**
il devrait y avoir un retour utilisateur (AlertBox)

**Captures d'écran** (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/fcf4af47-b39f-4cb5-a133-1d4db0f2b3fe)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/900e6d5b-1bd3-4a2a-9c44-0029137b15c9)

**Comment by TomDouaud** [comment]
Résolu avec la branche bug#83-BoutonAnnulerCreerQuestionCategorie (il fallait résoudre plusieurs bug en meme temps)
