### ISSUE TITLE
nom de categorie non strip

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#71]
## Description

lors de la créatin d'une categorie avec des espace devant ou apres le nom, la categorie est enregistrée tel quel

## Étape pour reproduire le bug

1. Aller sur la page 'creationQuestionEtCtagorie' tab categorie
2. Cliquez sur 'valider' 
3. Saisir dans le champs 'nom de la categorie' une string avant des espaces avant et/ou apres
4. **L'erreur apparait**

## Comportement attendu

la categorie devrait etre crée mais les espaces devrait etre supprimées

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/a29414c1-8c9f-49d0-a38d-49d1c8fafb7f)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/30cdd26e-20fc-4306-894d-9a2e3ccc8b7e)

**Comment by TomDouaud** [comment]
Résolu avec la branche bug#83-BoutonAnnulerCreerQuestionCategorie (j'ai pu corriger ca rapidement, ca ne valait pas un branche a elle seule)
