### ISSUE TITLE
colonne null quand pas assez d'info dans editerCategories

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#72]
## Description

Quand il n'y a pas assez de categories pour remplir la table, la colonne 'nombre de question' affiche null sur chaque ligne

## Étape pour reproduire le bug

1. Aller sur la page 'editerQuestions'
2. Mettre un filtre afin qu'il n'y est pas assez de catgories pour remplir la table
3. **L'erreur apparait**

## Comportement attendu

la colonne 'nombre de question' ne devrait pas afficher null sur les lignes vides

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/efe0830e-e7c7-43c9-808b-a51e15826ec9)

**Comment by TomDouaud** [comment]
bug résolu sur la branche Bug #72
