### ISSUE TITLE
Nouvelle Question n'apparait pas dans la liste des question à éditer

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#73]
## Description

Quand on créer une question avec une nouvelle catégorie, la question n'apparait pas dans la liste des questions à éditer.

## Étape pour reproduire le bug

1. Créer une nouvelle Catégorie valide
2. Créer une nouvelle Question valide avec cette Catégorie
3. Valider
4. **Message d'erreur dans la console**
5. Allez sur la page Editer Question
6. **La question n'apparait pas**

## Comportement attendu

La question créer doit apparaitre dans la liste de question que l'on peut éditer.

## Captures d'écran

Créer une question valide avec une nouvelle catégorie
![Créer une question valide avec une nouvelle catégorie](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/7ecb67a6-2341-4c73-a443-06cc9bdfb625)

Message d'erreur dans la console
![Message d'erreur dans la console](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/e278b4cc-5e14-4590-b590-cdd8d5513900)

Liste sans la question créer
![Liste sans la question créer](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/b086cb17-8d67-4b30-81b7-c24ee01b3454)

**Comment by TomDouaud** [comment]
Il y a plus d'erreur sur  l'étape 4 sur la branche bug#77, mais la question n'apparait toujours pas

**Comment by TomDouaud** [comment]
Résolu sur la branche bug#77
