### ISSUE TITLE
la supression d'une question ne met pas a jour l'affichage du nb de question contenue dans les categories

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#74]
## Description

Quand on supprime une question, l'affichage du nombre de question contenue dans les catgories n'est pas mis a jour

## Étape pour reproduire le bug

1. Aller sur la page 'editerQuestions'
2. Supprimer une question
3. Aller sur la page 'EditerCategories'
4. **L'erreur apparait**

## Comportement attendu

L'affichage du nombre de question contenue dans une ctagorie devrait etre mis a jour apres l'edition/suppression d'une categorie

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/c54bea98-c6c6-41a8-b9bc-6f6bd5449478)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/ed2076d1-23de-45a1-99c2-eebf3f9f2ba0)

**Comment by TomDouaud** [comment]
Bug résolu sur la branche bug#77 (bug ayant la meme cause que #91)
