### ISSUE TITLE
Le filtre ne filtre pas

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#76]
## Description

Le filtre ne filtre pas correctement les catégories

## Étape pour reproduire le bug

1. Aller sur la page Editer Catégorie
2. Saisir dans le champs du filtre `G`
3. **Aucune Catégorie apparait**

## Comportement attendu

Seul la catégorie Général apparaisse

## Captures d'écran (optionnel)

Toutes les catégories quand il n'y a pas de filtre
![Toutes les catégorie](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/40060dba-1f65-4c00-8c7d-00ade108d06c)

Filtre avec G et sans catégorie
![Filtre avec G et sans catégorie](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/bfc837d2-bb69-4431-b56a-fe860356d188)

**Comment by TomDouaud** [comment]
Closed avec la branche parametre par Lucas qui n'a pas internet
