### ISSUE TITLE
lors de la création d'une catégorie depuis la page editerCategories, erreur dans la console + mauvais tab

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#77]
## Description

Quand on veut créer une catégorie depuis la page editerCategories, il y a une erreur dans la console et la mauvaise tab est affichée

## Étape pour reproduire le bug

1. Aller sur la page 'editerCategories'
2. Cliquez sur 'créer une catégorie'
3. **L'erreur apparait**

## Comportement attendu

la tab de création de catégorie devrait s'afficher 

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/d521476d-0aa0-4299-9cc6-9958f6efc7f1)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/0023ebb7-3d19-4343-86b7-648682eceb39)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/279bcca4-08af-4fbd-9d5c-4280eef848c5)

**Comment by TomDouaud** [comment]
Résolu par @quentinformatique sur la branche bug#77
