### ISSUE TITLE
Le style du tableau

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#78]
## Description

Le tableau listant les catégorie devient blanc quand on filtre avec une catégorie inexistante

## Étape pour reproduire le bug

1. Aller sur la page Editer Catégorie
2. Saisir dans le champs de filtre `qpeziughqpaiuf` ou tout autre nom de catégorie inexistante
3. **L'erreur apparait**

## Comportement attendu

Le fond du tableau doit être de la même couleur que la reste du fond de la page.

## Captures d'écran (optionnel)

Tableau tout blanc
![Tableau tout blanc](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/e57ae3d9-cafb-4a4a-9624-861ebb01f5e5)

**Comment by TomDouaud** [comment]
bug résolu sur la branche Bug #72
