### ISSUE TITLE
erreur dans la console lors de la création d'une question avec la categorie generale

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#79]
## Description

lors de la création d'une question avec la categorie generale, il y a une erreur dans la question

## Étape pour reproduire le bug

1. Aller sur la page 'creationQuestion'
2. créer une question avec la categorie générale
3. **L'erreur apparait**

## Comportement attendu

il ne devrait pas y avoir d'erreur

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/42fa2006-8a17-432b-8eca-7db7e0881b68)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/bbb850a1-385a-4fbc-91ff-abe588b82e38)

**Comment by TomDouaud** [comment]
Résolu avec la branche bug#83-BoutonAnnulerCreerQuestionCategorie (résolu en meme temps que les autres bugs)
