### ISSUE TITLE
Modification Intitulé question

### ISSUE THREAD

**Issue by IUTLucas** [GroupeSAETPA1/Quiz#8]
## US

En tant qu'utilisateur
Je peux modifier le libelle d'une question existante
Afin de corriger une éventuelle erreur

### **TEST ACCEPTATION :**

![Image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/ba9bbea2-1a89-466c-90ac-9f109358817d)

**Cas nominal :** 

Étant donné un utilisateur
Il clique sur le bouton de modification du libelle de la  question
Une pop-up s'ouvre lui demandant le nouveau libelle

**Cas nominal :** 

Étant donné un utilisateur sur la page de changement de nom
Il clique sur confirmer en ayant rempli le champs 
Alors le libelle est modifier

**Cas limite :**

Etant donné  un utilisateur sur la page de changement de nom
Il clique sur annuler
Alors il revient sur le menu de changement de nom des question

**Cas d'erreur :**

Etant donné un utilisateur sur la page de changement de nom
Il clique sur confirmer sans avoir rempli le champ 
Alors une pop up apparait lui demande de le remplir

## Pondération

4

**Comment by Francois389** [comment]
"d'une question existante" ?

**Comment by IUTLucas** [comment]
En fonction des précisions sur la gestion des saisie des libellé donné lors de #41 rajouter un/plusieurs cas d'erreur

**Comment by quentinformatique** [comment]
le afin de ta user storie est trop précis, on peut modifier le nom pour d'autres raison que le rendre plus compéhensible

**Comment by Francois389** [comment]
TODO clique pour afficher la page de modifiaction

**Comment by TomDouaud** [comment]
c'est plus un pop-up mais une page dédiée a la modification de question
