### ISSUE TITLE
Mauvaise prise en compte du clique

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#80]
## Description

La prise en copte du clique est prise en compte au niveau de la maison et nom pas sur tout le groupe

## Étape pour reproduire le bug

1. Aller sur la page Editer
2. Cliquez sur la porte de la maison
4. **Vous ne revenait pas à l'accueil**

## Comportement attendu

Même si on clique à 1 ou 2 pixel de la maison le clique soit prise en compte

## Captures d'écran (optionnel)

Toute la partie hachurée en jaune n'est pas cliquable
![Capture d'écran 2023-11-12 175735](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/4f273263-014f-4496-af5b-a6109b3e0cac)

**Comment by CrabeNeo** [comment]
le bug est aussi présent sur les eux pages d'edition
