### ISSUE TITLE
bouton annuler creationQuestionetCategorie

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#83]
## Description

le bouton annuler dans la création de question ne fonctionne pas

## Étape pour reproduire le bug

1. Aller sur la page 'creationQuestionEtCategorie'
2. Cliquez sur 'annuler'
3. **L'erreur apparait**

## Comportement attendu

le bouton devrait annuler la création donc soit vider les champs soit retourner a la page précedente

**Comment by TomDouaud** [comment]
Résolu avec la branche bug#83-BoutonAnnulerCreerQuestionCategorie
