### ISSUE TITLE
la suppresion d'une catagorie ne supprime pas ses questions

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#84]
## Description

lors de la suppresion d'une categorie, les questions contenues ne sont pas suprimées

## Étape pour reproduire le bug

1. Aller sur la page 'editerCategories'
2. supprimer en une
3. aller dans editerQuestions
4. **L'erreur apparait**

## Comportement attendu

la suppresion d'une ctagorie devrait entrainer la suppresion des questions contenues

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/09de9274-64ef-45f1-977d-41827dd581dc)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/d2e17465-7b72-4249-8549-efa24b09b5f8)

**Comment by TomDouaud** [comment]
Bug réparé sur la branche bug#77
