### ISSUE TITLE
supprimer les categories rend impossible la suppression de questions

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#85]
## Description

quand on supprime une categorie, on ne peut plus supprimer des questions

## Étape pour reproduire le bug

1. Allez supprimer des categories
2. Cliquez sur 'editerQuestions'
3. cliquer sur supprimer une question
4. **L'erreur apparait**

## Comportement attendu

la question devrait etre supprimable (elle ne devrait pas etre la si la categorie supprimée est la sienne)

## Captures d'écran (optionnel)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/666e8259-77a2-43df-bd06-b43896e2600b)
![image](https://github.com/GroupeSAETPA1/Quiz/assets/80545291/a3c27a0e-221e-4fec-a2e0-9b9caf79489f)

**Comment by TomDouaud** [comment]
Bug réparé sur la branche bug#77
