### ISSUE TITLE
Modifier nom catégorie

### ISSUE THREAD

**Issue by quentinformatique** [GroupeSAETPA1/Quiz#9]
## US

En tant que utilisateur
Je peut modifier le nom d'une catégorie
Afin de les renommer si le nom ne convient plus

## Test d'acceptation

![Image](https://github.com/GroupeSAETPA1/Quiz/assets/124200637/3871031e-a6a6-43ef-8d5f-4d0fc5c94186)

**Cas normaux**

### GIVEN 

un utilisateur sur la page éditeur de questions

### WHEN 

il clique sur modifier une catégorie

### THEN

il voit la liste des catégories

___ 

### GIVEN 

un utilisateur sur la page modifier catégories

### WHEN 

il clique sur une catégorie qu'il souhaite modifier

### THEN

il peut changer ses informations

___

**Cas d'erreur**

### GIVEN 

un utilisateur sur la page modifier catégories

### WHEN 

il change le nom d'une catégorie par une saisie invalide et enregistre

### THEN

Un message d'erreur explicite apparait

## Pondération

5

**Comment by quentinformatique** [comment]
En tant que utilisateur 
Je peut modifier le nom d'une catégorie
Afin de les renommer

**Comment by Francois389** [comment]
"corriger une erreur" ?

**Comment by TomDouaud** [comment]
Il manque pas un cas d'erreur quand l'utilisateur mets un nom de catégorie vide ou invalide ?
