### ISSUE TITLE
Categorie Identique

### ISSUE THREAD

**Issue by IUTLucas** [GroupeSAETPA1/Quiz#95]
## Description

Comportement actuelle : une categorie est créé si elle a le meme nom avec un ou plusieurs espace (debut ou fin)

## Étape pour reproduire le bug

1. Aller sur la page creer categorie
2. Cliquez sur nouvelle categorie
3. Saisir dans le champ 'nom' puis 'nom '
4. La categorie nom et 'nom ' sont toutes les deux créées

Comportement attendu : une categorie est  considéré en double si il y a un espace a la fin ou au debut

**Comment by TomDouaud** [comment]
bug fixed sur la branche bug#95
