### ISSUE TITLE
Impossible de modifier une catégorie

### ISSUE THREAD

**Issue by Francois389** [GroupeSAETPA1/Quiz#97]
## Description

Il n'est pas possible de modifier une catégorie

## Étape pour reproduire le bug

1. Aller sur la page EditerCategories
2. Cliquez sur le bouton modifier d'une catégorie (autre que General)
3. Rajouter dans le champs `afd` ( truc random )
4. **L'erreur apparait**

## Comportement attendu

On me confirme la suppression de la catégorie et qu'on me renvoie sur la page EditerCategories

## Captures d'écran (optionnel)

![image](https://github.com/GroupeSAETPA1/Quiz/assets/75416431/5272f1ef-6185-4729-893d-46aa788de8d9)

**Comment by quentinformatique** [comment]
fixed, du a une condition inversée dans controlleurEditerCategorie
